### ISSUE TITLE
Typhoon Type Projectile Spam Invisibility

### ISSUE THREAD

**Issue by gitdnd** [robinsch/WoWFix335#2]
Reproduction steps:
-Cast Typhoon without cooldown in quick succession while on the ground (for some reason it works while jumping)
Expected result:
-Projectile appears and is visible
Actual result:
-Projectile is invisible but still deals damage

https://streamable.com/cgnna9

**Comment by robinsch** [comment]
I found a fix for it but I don't think it is feasible to be converted to ASM:
https://streamable.com/65bmve
